server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # No cache for development
    add_header Cache-Control "no-store, no-cache, must-revalidate";

    # Correct MIME types for JS modules
    types {
        text/html html;
        text/css css;
        application/javascript js mjs;
        application/json json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip compression
    gzip on;
    gzip_types text/html text/css application/javascript application/json;
}
